# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9

    working_directory: ~/repo

    steps:
      - checkout

      # We aren't caching, because I want to re-download everything to test this repo.
      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements-dev.txt

      - run:
          name: nox
          command: |
            . .venv/bin/activate
            python -m nox
