version: 2.1
workflows:
  commit:
    jobs:
      -build
  daily:
    triggers:
      - schedule:
          cron: "5 13 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      -build
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      # We aren't caching, because I want to re-download everything to test this repo.
      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements-dev.txt
      - run:
          name: nox
          command: |
            . .venv/bin/activate
            python -m nox
      - store_test_results:
          path: build/pytest
